import { createSlice, PayloadAction } from '@reduxjs/toolkit';

/**
 * Interface for a Product object.
 * Defines the structure of product data within the Redux state.
 */
interface Product {
  id: number;
  code: string;
  name: string;
  value: number;
}

/**
 * Interface for the state of the products slice.
 * Manages a list of products, their loading status, and any errors.
 * (Currently, this slice is mostly a placeholder as RTK Query handles most data fetching).
 */
interface ProductsState {
  products: Product[];
  status: 'idle' | 'loading' | 'succeeded' | 'failed';
  error: string | null;
}

// Initial state for the products slice.
const initialState: ProductsState = {
  products: [],
  status: 'idle',
  error: null,
};

/**
 * Redux slice for managing products.
 * While RTK Query handles API interactions, this slice can be used for
 * any local product state management or direct updates if needed.
 */
export const productsSlice = createSlice({
  name: 'products', // Name of the slice
  initialState,    // Initial state
  reducers: {
    /**
     * Example reducer to add a product to the state.
     * This is for demonstration; actual product data management is via RTK Query.
     */
    addProduct: (state, action: PayloadAction<Product>) => {
      state.products.push(action.payload);
    },
    // More reducers and async thunks would go here for actual API interaction
  },
});

// Export actions generated by createSlice
export const { addProduct } = productsSlice.actions;

// Export the reducer for the store
export default productsSlice.reducer;
