import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

/**
 * Interface representing a Product structure for API communication.
 */
interface Product {
  id?: number; // Optional as it's not present during creation
  code: string;
  name: string;
  value: number;
}

/**
 * RTK Query API slice for interacting with product-related endpoints.
 * It provides hooks for fetching, creating, updating, and deleting products.
 */
export const productApi = createApi({
  reducerPath: 'productApi', // Unique key for the RTK Query reducer
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:8080/' }), // Base URL for all API requests
  tagTypes: ['Product'], // Used for caching and invalidation strategies
  endpoints: (builder) => ({
    /**
     * Query to get all products.
     * Provides 'Product' tag for re-fetching.
     */
    getProducts: builder.query<Product[], void>({
      query: () => 'products', // API endpoint path
      providesTags: ['Product'],
    }),
    /**
     * Query to get a single product by ID.
     * Provides 'Product' tag with specific ID for re-fetching.
     */
    getProductById: builder.query<Product, number>({
      query: (id) => `products/${id}`,
      providesTags: (result, error, id) => [{ type: 'Product', id }],
    }),
    /**
     * Mutation to create a new product.
     * Invalidates 'Product' tag to trigger re-fetch of product lists.
     */
    createProduct: builder.mutation<Product, Omit<Product, 'id'>>({
      query: (newProduct) => ({
        url: 'products',
        method: 'POST',
        body: newProduct,
      }),
      invalidatesTags: ['Product'],
    }),
    /**
     * Mutation to update an existing product.
     * Invalidates 'Product' tag (with specific ID) to trigger re-fetch of relevant product data.
     */
    updateProduct: builder.mutation<Product, Product>({
      query: (updatedProduct) => ({
        url: `products/${updatedProduct.id}`,
        method: 'PUT',
        body: updatedProduct,
      }),
      invalidatesTags: (result, error, { id }) => [{ type: 'Product', id }],
    }),
    /**
     * Mutation to delete a product by ID.
     * Invalidates 'Product' tag to trigger re-fetch of product lists.
     */
    deleteProduct: builder.mutation<void, number>({
      query: (id) => ({
        url: `products/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Product'],
    }),
  }),
});

// Export hooks generated by RTK Query for each endpoint
export const {
  useGetProductsQuery,
  useGetProductByIdQuery,
  useCreateProductMutation,
  useUpdateProductMutation,
  useDeleteProductMutation,
} = productApi;

