import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { Product } from '../products/productApi';

/**
 * Interface representing a ProductionSuggestion structure for API communication.
 */
interface ProductionSuggestion {
  product: Product; // The product suggested for production
  quantityProducible: number; // The quantity of the product that can be produced
  totalValue: number; // The total value of the producible quantity
}

/**
 * RTK Query API slice for interacting with production-related endpoints.
 * Specifically, it provides a hook for fetching production suggestions.
 */
export const productionApi = createApi({
  reducerPath: 'productionApi', // Unique key for the RTK Query reducer
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:8080/' }), // Base URL for all API requests
  tagTypes: ['Production'], // Used for caching and invalidation strategies
  endpoints: (builder) => ({
    /**
     * Query to get a list of suggested products for production.
     * Provides 'Production' tag for re-fetching.
     */
    getProductionSuggestions: builder.query<ProductionSuggestion[], void>({
      query: () => 'production/suggested', // API endpoint path for production suggestions
      providesTags: ['Production'],
    }),
  }),
});

// Export hooks generated by RTK Query for each endpoint
export const { useGetProductionSuggestionsQuery } = productionApi;
