import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

/**
 * Interface representing a RawMaterial structure for API communication.
 */
interface RawMaterial {
  id?: number; // Optional as it's not present during creation
  code: string;
  name: string;
  quantityInStock: number;
}

/**
 * RTK Query API slice for interacting with raw material-related endpoints.
 * It provides hooks for fetching, creating, updating, and deleting raw materials.
 */
export const rawMaterialApi = createApi({
  reducerPath: 'rawMaterialApi', // Unique key for the RTK Query reducer
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:8080/' }), // Base URL for all API requests
  tagTypes: ['RawMaterial'], // Used for caching and invalidation strategies
  endpoints: (builder) => ({
    /**
     * Query to get all raw materials.
     * Provides 'RawMaterial' tag for re-fetching.
     */
    getRawMaterials: builder.query<RawMaterial[], void>({
      query: () => 'rawmaterials', // API endpoint path
      providesTags: ['RawMaterial'],
    }),
    /**
     * Query to get a single raw material by ID.
     * Provides 'RawMaterial' tag with specific ID for re-fetching.
     */
    getRawMaterialById: builder.query<RawMaterial, number>({
      query: (id) => `rawmaterials/${id}`,
      providesTags: (result, error, id) => [{ type: 'RawMaterial', id }],
    }),
    /**
     * Mutation to create a new raw material.
     * Invalidates 'RawMaterial' tag to trigger re-fetch of raw material lists.
     */
    createRawMaterial: builder.mutation<RawMaterial, Omit<RawMaterial, 'id'>>({
      query: (newRawMaterial) => ({
        url: 'rawmaterials',
        method: 'POST',
        body: newRawMaterial,
      }),
      invalidatesTags: ['RawMaterial'],
    }),
    /**
     * Mutation to update an existing raw material.
     * Invalidates 'RawMaterial' tag (with specific ID) to trigger re-fetch of relevant raw material data.
     */
    updateRawMaterial: builder.mutation<RawMaterial, RawMaterial>({
      query: (updatedRawMaterial) => ({
        url: `rawmaterials/${updatedRawMaterial.id}`,
        method: 'PUT',
        body: updatedRawMaterial,
      }),
      invalidatesTags: (result, error, { id }) => [{ type: 'RawMaterial', id }],
    }),
    /**
     * Mutation to delete a raw material by ID.
     * Invalidates 'RawMaterial' tag to trigger re-fetch of raw material lists.
     */
    deleteRawMaterial: builder.mutation<void, number>({
      query: (id) => ({
        url: `rawmaterials/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['RawMaterial'],
    }),
  }),
});

// Export hooks generated by RTK Query for each endpoint
export const {
  useGetRawMaterialsQuery,
  useGetRawMaterialByIdQuery,
  useCreateRawMaterialMutation,
  useUpdateRawMaterialMutation,
  useDeleteRawMaterialMutation,
} = rawMaterialApi;
