import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
// Importing types for consistency and clarity, though not strictly required for RTK Query itself
import type { Product } from '../products/productApi';
import type { RawMaterial } from '../rawMaterials/rawMaterialApi';

/**
 * Interface representing a ProductRawMaterial association structure for API communication.
 */
interface ProductRawMaterial {
  id?: number; // Optional as it's not present during creation
  product: Product; // The associated product
  rawMaterial: RawMaterial; // The associated raw material
  quantityNeeded: number; // Quantity of raw material needed for one product unit
}

/**
 * RTK Query API slice for interacting with product-raw material association endpoints.
 * It provides hooks for fetching, creating, updating, and deleting these associations.
 */
export const productRawMaterialApi = createApi({
  reducerPath: 'productRawMaterialApi', // Unique key for the RTK Query reducer
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:8080/' }), // Base URL for all API requests
  tagTypes: ['ProductRawMaterial'], // Used for caching and invalidation strategies
  endpoints: (builder) => ({
    /**
     * Query to get all product-raw material associations.
     * Provides 'ProductRawMaterial' tag for re-fetching.
     */
    getProductRawMaterials: builder.query<ProductRawMaterial[], void>({
      query: () => 'productrawmaterials',
      providesTags: ['ProductRawMaterial'],
    }),
    /**
     * Query to get a single product-raw material association by ID.
     * Provides 'ProductRawMaterial' tag with specific ID for re-fetching.
     */
    getProductRawMaterialById: builder.query<ProductRawMaterial, number>({
      query: (id) => `productrawmaterials/${id}`,
      providesTags: (result, error, id) => [{ type: 'ProductRawMaterial', id }],
    }),
    /**
     * Mutation to create a new product-raw material association.
     * Invalidates 'ProductRawMaterial' tag to trigger re-fetch of association lists.
     */
    createProductRawMaterial: builder.mutation<ProductRawMaterial, Omit<ProductRawMaterial, 'id'>>({
      query: (newAssociation) => ({
        url: 'productrawmaterials',
        method: 'POST',
        body: newAssociation,
      }),
      invalidatesTags: ['ProductRawMaterial'],
    }),
    /**
     * Mutation to update an existing product-raw material association.
     * Invalidates 'ProductRawMaterial' tag (with specific ID) to trigger re-fetch of relevant association data.
     */
    updateProductRawMaterial: builder.mutation<ProductRawMaterial, ProductRawMaterial>({
      query: (updatedAssociation) => ({
        url: `productrawmaterials/${updatedAssociation.id}`,
        method: 'PUT',
        body: updatedAssociation,
      }),
      invalidatesTags: (result, error, { id }) => [{ type: 'ProductRawMaterial', id }],
    }),
    /**
     * Mutation to delete a product-raw material association by ID.
     * Invalidates 'ProductRawMaterial' tag to trigger re-fetch of association lists.
     */
    deleteProductRawMaterial: builder.mutation<void, number>({
      query: (id) => ({
        url: `productrawmaterials/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['ProductRawMaterial'],
    }),
    /**
     * Query to get product-raw material associations for a specific product ID.
     * This endpoint is crucial for displaying and managing associations within a product's form.
     * Provides 'ProductRawMaterial' tag with specific product ID for re-fetching.
     */
    getProductRawMaterialsByProductId: builder.query<ProductRawMaterial[], number>({
      query: (productId) => `productrawmaterials/byProduct/${productId}`, // Backend path for filtering
      providesTags: (result, error, productId) => [{ type: 'ProductRawMaterial', productId }],
    }),
  }),
});

// Export hooks generated by RTK Query for each endpoint
export const {
  useGetProductRawMaterialsQuery,
  useGetProductRawMaterialByIdQuery,
  useCreateProductRawMaterialMutation,
  useUpdateProductRawMaterialMutation,
  useDeleteProductRawMaterialMutation,
  useGetProductRawMaterialsByProductIdQuery,
} = productRawMaterialApi;
